name = "my-subs-2"
main = "src/server/index.ts"
compatibility_date = "2024-09-01"

# 静态前端 SPA 资产托管 (Cloudflare Workers Assets)
[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

# D1 数据库绑定 (主数据存储与请求日志)
[[d1_databases]]
binding = "DB"
database_name = "test_d1_subs"
database_id = "5780b764-2d82-4890-918c-6b57e419f987"

# KV 命名空间绑定 (边缘极速缓存层)
[[kv_namespaces]]
binding = "SUBS_KV"
id = "42caa645a5744ac392a0529b2ee8b68f"

[vars]
ADMIN_TOKEN = "admin123456"
APP_SECRET = "a_secure_random_key_for_mysubs_v2_encryption_32"
SECURE_ENTRANCE = "/secret_gate"
# CDN_HEADER_NAME = "x-cdn-request-host"
