name = "my-subs"
main = "src/server/index.ts"
compatibility_date = "2024-09-01"

# 静态前端 SPA 资产托管 (Cloudflare Workers Assets)
[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

# D1 数据库绑定 (主数据存储与请求日志)
[[d1_databases]]
binding = "DB"
database_name = "my_subs"
database_id = "65d93529-bdcd-4e39-bc95-f9677eb379e5"

# KV 命名空间绑定 (边缘极速缓存层)
[[kv_namespaces]]
binding = "SUBS_KV"
id = "16108832d2984701ac2cdb257e2ef613"

[vars]
# ADMIN_TOKEN = ""
# APP_SECRET = " "
SECURE_ENTRANCE = "/KorinSubs"
# CDN_HEADER_NAME = "x-cdn-request-host"
